# LocalStack endpoint override
quarkus.sqs.endpoint-override=http://localhost:4566
quarkus.dynamodb.endpoint-override=http://localhost:4566

# Region
quarkus.sqs.aws.region=eu-central-1
quarkus.dynamodb.aws.region=eu-central-1

# Index commons module for Quarkus / GraalVM reflection discovery
quarkus.index-dependency.commons.group-id=com.alexthesis
quarkus.index-dependency.commons.artifact-id=commons

# DynamoDB table names
thesis.dynamodb.ledger-table=thesis_ledger

